### ISSUE TITLE
Unable to run examples?

### ISSUE THREAD

**Issue by bollu** [lambdacube3d/lambdacube-edsl#10]
I tried to compile and run the examples, but the fail at

```
Common/Utils.hs:9:8:
    Could not find module ‘Graphics.Rendering.OpenGL.Raw.Core32’
    Use -v to see a list of the files searched for.

FX.hs:7:15:
    Could not find module ‘LambdaCube.GL’
    Use -v to see a list of the files searched for.

FX.hs:8:15:
    Could not find module ‘LambdaCube.GL.Mesh’
    Use -v to see a list of the files searched for.
```

Even though I've installed `lambdacube-core`. What am I missing?

**Comment by bollu** [comment]
Actually, ignore this. I was trying to set it up from scratch, but I'm not able to get the "getting started" examples to work at all, so this comes later.

after a successful
```
cabal install lambdacube-gl
cabal install GLFW-b
```

Compiling `Hello.hs` leads to

```
Hello.hs:14:8:
    Could not find module ‘Paths_lambdacube_samples’
    Use -v to see a list of the files searched for.
```

I'm not sure where the module is being defined. Can I have some help?

**Comment by cobbpg** [comment]
Oh, you're looking at the samples for the old EDSL system, which are not compatible with the new GL backend. Check the [examples](https://github.com/lambdacube3d/lambdacube-gl/tree/master/examples) directory within `lambdacube-gl` (as the [getting started guide](http://lambdacube3d.com/getting-started) suggests just above the screenshot), which should work as advertised.

**Comment by bollu** [comment]
Okay, new error now. I'm following the getting started guide, at the point where i'm supposed to build `Hello.hs`

```
[1 of 1] Compiling Main             ( Hello.hs, Hello.o )

Hello.hs:20:26:
    No instance for (FromJSON LambdaCube.IR.Pipeline)
      arising from a use of ‘decodeStrict’
    In the first argument of ‘(<$>)’, namely ‘decodeStrict’
    In a stmt of a 'do' block:
      Just pipelineDesc <- decodeStrict <$> SB.readFile "hello.json"
    In the expression:
      do { Just pipelineDesc <- decodeStrict
                                <$> SB.readFile "hello.json";
           win <- initWindow "LambdaCube 3D DSL Hello World" 640 640;
           let inputSchema = makeSchema $ ...;
           storage <- allocStorage inputSchema;
           .... }
```

It looks like de-serialization isn't happening?

**Comment by csabahruska** [comment]
if you use it from github then try to install it with -fexample

cabal install -fexample

**Comment by bollu** [comment]
Nope, I'm installing it using Cabal (hackage). Same error, unfortunately. Any idea where it might be going wrong?

**Comment by csabahruska** [comment]
The -fexample flag will be included in the next release, it's not yet on the hackage version of lambdacube-gl. You have to work from gtihub for now.

### install
> git clone https://github.com/lambdacube3d/lambdacube-ir.git
> cd lambdacube-ir; cabal install; cd ..
> git clone https://github.com/lambdacube3d/lambdacube-gl.git
> cd lambdacube-gl; cabal install -fexample

### run
> cd examples; ../dist/build/lambdacube-gl-hello/lambdacube-gl-hello

**Comment by bollu** [comment]
Thanks a ton for the detailed instructions! I got it up and running :) Really appreciate it.
